{% set name = "nirtorch" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nirtorch-{{ version }}.tar.gz
  sha256: 445a41e14547fd5f45714218591b321622679a92ac17dc4d3e42b252c93cc44e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pytorch
    - nir

test:
  imports:
    - nirtorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Neuromorphic Intermediate Representation
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/neuromorphs/NIRTorch/

extra:
  recipe-maintainers:
    - Tobias-Fischer
