{% set name = "nirtorch" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nirtorch-{{ version }}.tar.gz
  sha256: a0a7c485c0cb523a257a68b881c83d3710a471ad896188879a1bb722d47db2bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - pytorch
    - nir

test:
  imports:
    - nirtorch
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Neuromorphic Intermediate Representation
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/neuromorphs/NIRTorch/

extra:
  recipe-maintainers:
    - Tobias-Fischer
